<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="ToolsPages.Xml.XmlConAspNet.Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        table tr th
        {
            text-align: right;
        }
        
        table tr td
        {
            text-align:left;
        }
    </style>
</head>
<body>
    <%--Me funciono en Windows 8 hay que agregar IIS_IUSRS--%>
    <form id="form1" runat="server">
    <div>
        <center>
            <fieldset style="width:400px;">
                <legend>XML Database Demo</legend>
                <table border="1" width="100%">
                    <tr>
                        <th>Roll No :</th>
                        <td>
                            <asp:TextBox runat="server" ID="txtID" />
                        </td>
                    </tr>
                    <tr>
                        <th>First Name :</th>
                        <td>
                            <asp:TextBox runat="server" ID="txtFirstName" />
                        </td>
                    </tr>
                    <tr>
                        <th>Last Name :</th>
                        <td>
                            <asp:TextBox runat="server" ID="txtLastName" />
                        </td>
                    </tr>
                    <tr>
                        <th>City :</th>
                        <td>
                            <asp:DropDownList runat="server" ID="ddlCity">
                                <asp:ListItem Text="Surat" />
                                <asp:ListItem Text="Baroda" />
                                <asp:ListItem Text="Ahmedbad" />
                            </asp:DropDownList>
                        </td>
                    </tr>
                    <tr>
                        <th>Gender: </th>
                        <td>
                            <asp:RadioButtonList runat="server" ID="rblGender" RepeatDirection="Horizontal">
                                <asp:ListItem Text="Male" />
                                <asp:ListItem Text="Female" />
                            </asp:RadioButtonList>
                        </td>
                    </tr>
                    <tr>
                        <th>Pincode :</th>
                        <td>
                            <asp:TextBox runat="server" ID="txtPincode" />
                        </td>
                    </tr>
                    <tr>
                        <th>Mobile No :</th>
                        <td>
                            <asp:TextBox runat="server" ID="txtMobileNo" />
                        </td>
                    </tr>
                    <tr>
                        <th colspan="2">
                            <asp:Button Text="Insert" runat="server" onclick="Unnamed1_Click" ID="btnSubmit" />
                        </th>
                    </tr>
                </table>
                <br />
                <asp:GridView
                    ID="GridView1"
                    runat="server"
                    CellPadding="4"
                    ForeColor="#333333" 
                    GridLines="None"
                    AllowPaging="True"
                    AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True" 
                    onrowcancelingedit="GridView1_RowCancelingEdit" 
                    onrowediting="GridView1_RowEditing"
                    onrowupdating="GridView1_RowUpdating" 
                    PageSize="5" onpageindexchanging="GridView1_PageIndexChanging" 
                    onrowdeleting="GridView1_RowDeleting" >
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:TemplateField HeaderText="RollNo">
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("ID") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="FirstName">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEditFirstName" runat="server" Text='<%# Bind("FirstName") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("FirstName") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="LastName">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEditLastName" runat="server" Text='<%# Bind("LastName") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label3" runat="server" Text='<%# Bind("LastName") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="City">
                            <EditItemTemplate>
                                <asp:DropDownList
                                    ID="ddlEditCity"
                                    runat="server" 
                                    SelectedValue='<%# Bind("City") %>'>
                                    <asp:ListItem Text="Surat" />
                                    <asp:ListItem Text="Baroda" />
                                    <asp:ListItem Text="Ahmedbad" />
                                </asp:DropDownList>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label4" runat="server" Text='<%# Bind("City") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Gender">
                            <EditItemTemplate>
                                <asp:RadioButtonList
                                    ID="rblEditGender"
                                    runat="server" 
                                    RepeatDirection="Horizontal"
                                    SelectedValue='<%# Bind("Gender") %>'>
                                    <asp:ListItem>Male</asp:ListItem>
                                    <asp:ListItem>Female</asp:ListItem>
                                </asp:RadioButtonList>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label5" runat="server" Text='<%# Bind("Gender") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Pincode">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEditPincode" runat="server" Text='<%# Bind("Pincode") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label6" runat="server" Text='<%# Bind("Pincode") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="MobileNo">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEditMobileNo" runat="server" Text='<%# Bind("MobileNo") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label7" runat="server" Text='<%# Bind("MobileNo") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
            </fieldset>
        </center>
    </div>
    </form>
</body>
</html>
